"""create_bonds_table

Revision ID: 470bf7392c9f
Revises: 4604563dca89
Create Date: 2025-10-22 19:34:42.365656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470bf7392c9f'
down_revision: Union[str, Sequence[str], None] = '4604563dca89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('bond_id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for each bond.'),
    sa.Column('atom1_symbol', sa.String(length=3), nullable=False, comment='Chemical symbol of the first atom.'),
    sa.Column('atom2_symbol', sa.String(length=3), nullable=False, comment='Chemical symbol of the second atom.'),
    sa.Column('bond_type', sa.String(length=20), nullable=False, comment='Type of bond: Nonpolar Covalent, Polar Covalent, or Ionic.'),
    sa.Column('bond_orders', sa.String(length=10), nullable=False, comment="Possible bond orders as comma-separated string (e.g., '1,2,3')."),
    sa.Column('delta_en', sa.Float(), nullable=False, comment='Electronegativity difference (ΔEN).'),
    sa.Column('can_form', sa.Boolean(), nullable=False, comment='Whether the bond can form based on rules.'),
    sa.PrimaryKeyConstraint('bond_id')
    )
    op.create_index('ix_bonds_atom1_symbol', 'bonds', ['atom1_symbol'], unique=False)
    op.create_index('ix_bonds_atom2_symbol', 'bonds', ['atom2_symbol'], unique=False)
    op.add_column('atoms', sa.Column('electronegativity', sa.Float(), nullable=True, comment='Pauling electronegativity value.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atoms', 'electronegativity')
    op.drop_index('ix_bonds_atom2_symbol', table_name='bonds')
    op.drop_index('ix_bonds_atom1_symbol', table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
