"""Create atoms table

Revision ID: 687159da0351
Revises: 
Create Date: 2025-10-02 16:23:52.371621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687159da0351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atoms',
    sa.Column('atom_id', sa.Integer(), nullable=False, comment='Unique identifier for each atom, corresponds to atomic number.'),
    sa.Column('element_symbol', sa.String(length=3), nullable=False, comment='Chemical symbol of the element (e.g., H, He).'),
    sa.Column('protons', sa.Integer(), nullable=False, comment='Number of protons in the nucleus.'),
    sa.Column('electrons', sa.Integer(), nullable=False, comment='Number of electrons orbiting the nucleus.'),
    sa.Column('neutrons', sa.Integer(), nullable=False, comment='Number of neutrons in the nucleus.'),
    sa.Column('electron_config', sa.String(length=100), nullable=True, comment='The electron configuration string.'),
    sa.Column('atomic_mass', sa.Float(), nullable=False, comment='The standard atomic weight of the element.'),
    sa.Column('atomic_radius', sa.Float(), nullable=True, comment='The atomic radius in picometers (defaulted to 0).'),
    sa.Column('valence_electrons', sa.Integer(), nullable=True, comment='The number of electrons in the outermost shell.'),
    sa.PrimaryKeyConstraint('atom_id'),
    sa.UniqueConstraint('element_symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atoms')
    # ### end Alembic commands ###
